# AI Assistance Pipeline Configuration
content_generation:
  enabled: true
  triggers:
    - new_package_detected
    - documentation_update_needed
    - manual_request
  workflows:
    package_analysis:
      priority: high
      timeout: 10m
    build_process:
      priority: high
      timeout: 15m
    configuration:
      priority: medium
      timeout: 10m
    dependency_mapping:
      priority: medium
      timeout: 20m

quality_enhancement:
  enabled: true
  checks:
    style_consistency:
      threshold: 0.90
      frequency: continuous
    technical_accuracy:
      threshold: 0.95
      frequency: on_change
    clarity:
      threshold: 0.85
      frequency: continuous
    cross_references:
      threshold: 0.99
      frequency: hourly

