# Documentation Template Validation Configuration

# Required Sections
required_sections:
  - A1_basic_information
  - A2_description
  - B7_system_requirements
  - B8_required_packages
  - C13_source_verification
  - D19_build_environment
  - D21_build_commands
  - F31_installation_process
  - H39_security_considerations

# Section Content Validation
content_rules:
  package_name:
    required: true
    pattern: '^[a-zA-Z0-9_-]+$'
  version:
    required: true
    pattern: '^[0-9]+\.[0-9]+(\.[0-9]+)?$'
  source_verification:
    required_fields:
      - checksum
      - verification_process
  build_commands:
    min_steps: 1
    requires_verification: true

# Quality Metrics
quality_checks:
  - completeness
  - technical_accuracy
  - clarity
  - consistency
  - up_to_date

# Cross-reference Validation
xref_validation:
  check_internal_links: true
  check_external_links: true
  verify_package_references: true

# AI Assistance Integration
ai_validation:
  - completeness_check
  - technical_accuracy_review
  - consistency_verification
  - update_recommendation

# Error Levels
error_levels:
  - critical
  - warning
  - suggestion

# Validation Output
output_format:
  type: json
  include_statistics: true
  include_recommendations: true

