# AI Workflow Manager Configuration
version: '1.0'

# Core Integration Components (Phase 1)
core_components:
  service_infrastructure:
    enabled: true
    components:
      - validation_service
      - content_generation
      - testing_framework
    initialization_order:
      - validation_pipeline
      - review_pipeline
      - update_pipeline
      - test_framework

# Service Configuration
services:
  validation_service:
    pipeline: validation_pipeline.yaml
    priority: high
    required: true
    initialization_checks:
      - schema_validation
      - content_completeness
      - cross_reference_integrity
      - quality_metrics

  content_generation:
    pipeline: update_pipeline.yaml
    priority: medium
    required: true
    features:
      - package_analysis
      - build_documentation
      - configuration_docs
      - dependency_mapping

  review_service:
    pipeline: review_pipeline.yaml
    priority: medium
    required: true
    features:
      - technical_review
      - completeness_check
      - quality_assessment
      - cross_reference_check

# Integration Settings
integration:
  validation_criteria:
    technical_accuracy: 0.95
    completeness: 0.90
    clarity: 0.85
    consistency: 0.95

  workflows:
    pre_commit:
      enabled: true
      checks:
        - quick_validation
        - style_check
    post_commit:
      enabled: true
      checks:
        - deep_analysis
        - cross_reference_check
    scheduled:
      enabled: true
      interval: 30m
      checks:
        - comprehensive_review
        - update_recommendations

# Monitoring and Metrics
monitoring:
  enabled: true
  metrics:
    - validation_accuracy
    - response_time
    - completion_rate
    - error_rate
  alerts:
    validation_failure:
      threshold: 0.05
      notify: true
    response_time:
      threshold: 2s
      notify: true

# Testing Framework
testing:
  enabled: true
  components:
    - validation_pipeline
    - content_generation
    - review_process
  test_types:
    - unit_tests
    - integration_tests
    - performance_tests
  criteria:
    accuracy: 0.95
    response_time: 2s
    coverage: 0.90

# Error Handling
error_handling:
  retry_attempts: 3
  backoff_interval: 5s
  failure_threshold: 0.1
  recovery:
    enabled: true
    strategy: gradual_recovery

# Performance Settings
performance:
  max_concurrent_operations: 10
  timeout: 30s
  batch_size: 100
  optimization:
    enabled: true
    strategy: adaptive

# AI Workflow Manager Configuration
version: '1.0'

# Global Settings
global:
  log_level: info
  metrics_enabled: true
  feedback_collection: true
  auto_remediation: false

# Workflow Orchestration
orchestration:
  triggers:
    pre_commit:
      - validate_technical_content
      - check_completeness
      - verify_style
    post_commit:
      - deep_analysis
      - cross_reference_validation
    scheduled:
      cron: "0 0 * * *"  # Daily at midnight
      tasks:
        - comprehensive_review
        - update_detection
        - quality_metrics_collection

  pipelines:
    validation:
      config: validation_pipeline.yaml
      priority: high
      timeout: 300  # 5 minutes
    review:
      config: review_pipeline.yaml
      priority: medium
      timeout: 600  # 10 minutes
    update:
      config: update_pipeline.yaml
      priority: low
      timeout: 1800  # 30 minutes

# Integration Points
integration:
  template_sections:
    - section: "A.*"
      validators:
        - basic_info_check
        - version_validation
    - section: "B.*"
      validators:
        - dependency_check
        - compatibility_validation
    - section: "C.*"
      validators:
        - source_verification
        - patch_validation
    - section: "D.*"
      validators:
        - build_process_check
        - command_validation
    - section: "[E-J].*"
      validators:
        - content_completeness
        - technical_accuracy

# Metrics Collection
metrics:
  collectors:
    - name: accuracy
      threshold: 0.95
      alert_threshold: 0.90
    - name: completeness
      threshold: 0.90
      alert_threshold: 0.85
    - name: consistency
      threshold: 0.95
      alert_threshold: 0.90

# Error Handling
error_handling:
  retry:
    max_attempts: 3
    backoff: exponential
  notification:
    channels:
      - slack
      - email
    threshold: error

# System Health
health_check:
  interval: 300  # 5 minutes
  endpoints:
    - validation_service
    - review_service
    - update_service
  actions:
    on_failure:
      - restart_service
      - notify_admin

