# Test Runner Configuration
# Created: 2025-05-31T16:20:01Z
# Version: 1.0.0

# Resource allocation configuration
resource_allocation:
  computation:
    cpu:
      min_cores: 1
      max_cores: 4
      default_usage: 50
      warning_threshold: 80
      critical_threshold: 90
    
    memory:
      min_gb: 1
      max_gb: 8
      default_gb: 4
      warning_threshold: 80
      critical_threshold: 90
    
    storage:
      min_gb: 5
      max_gb: 50
      default_gb: 20
      warning_threshold: 80
      critical_threshold: 90
    
    max_concurrent_tests: 4

# Test execution configuration
test_execution:
  timeouts:
    default: 300  # seconds
    minimum: 60   # seconds
    maximum: 3600 # seconds
  
  retry:
    max_attempts: 3
    delay: 5  # seconds
  
  parallel:
    enabled: true
    max_workers: 4

# Result collection configuration
result_collection:
  storage:
    path: "results"
    retention_days: 90
  
  formats:
    - junit-xml
    - json
  
  metrics:
    collection_interval: 5  # seconds
    aggregation_interval: 60  # seconds

# Logging configuration
logging:
  level: INFO
  file: "test_runner.log"
  rotation:
    max_size: "10MB"
    backup_count: 5
  
  metrics:
    enabled: true
    interval: 60  # seconds

# Integration configuration
integration:
  build_system:
    hooks:
      - pre_build
      - post_build
      - error_handler
    
    environment:
      setup: true
      cleanup: true
  
  monitoring:
    enabled: true
    metrics:
      - cpu_usage
      - memory_usage
      - io_operations
      - test_duration
    
    alerts:
      resource_threshold: 80
      error_threshold: 5

# Quality gates
quality_gates:
  coverage:
    minimum: 80
    target: 90
  
  performance:
    max_duration: 300  # seconds
    max_resource_usage: 80  # percent
  
  reliability:
    min_pass_rate: 95
    max_flaky_rate: 5

# Cleanup configuration
cleanup:
  enabled: true
  triggers:
    - test_completion
    - resource_threshold
    - system_shutdown
  
  actions:
    - temp_files
    - resource_release
    - environment_reset

# Reporting configuration
reporting:
  formats:
    - html
    - json
    - junit
  
  notifications:
    enabled: true
    channels:
      - log
      - email
    
    triggers:
      - test_failure
      - resource_warning
      - quality_gate_failure

