# Testing Configuration
integration_tests:
  validation_pipeline:
    enabled: true
    frequency: hourly
    coverage_threshold: 0.95
  assistance_pipeline:
    enabled: true
    frequency: daily
    coverage_threshold: 0.90

performance_tests:
  response_time:
    enabled: true
    frequency: hourly
    thresholds:
      validation: 2s
      generation: 5s
      enhancement: 3s
  batch_processing:
    enabled: true
    frequency: daily
    threshold: 30m

quality_tests:
  documentation:
    enabled: true
    frequency: daily
    thresholds:
      completeness: 0.98
      accuracy: 0.95
      consistency: 0.90
  cross_references:
    enabled: true
    frequency: hourly
    accuracy_threshold: 0.99

